image: registry.gitlab.com/fdroid/ci-images-repomaker:latest

pep8:
  script:
    - ./tests/test-pep8.sh

pylint:
  script:
    - ./tests/test-pylint.sh

units:
  cache:
    paths:
      - /usr/local/lib/python3.5/dist-packages
      - node_modules

  before_script:
    - ./setup.sh
    - pip3 install -r requirements-dev.txt
    - npm install --user

  script:
    - ./tests/test-units.sh
    - ./tests/assert-test-confinement.sh
