image: registry.gitlab.com/fdroid/ci-images-repomaker:latest

cache:
  paths:
    - /usr/local/lib/python3.4/dist-packages

before_script:
  - ./setup.sh
  - pip3 install -r requirements-dev.txt

test:
  script:
    - ./run-tests.sh
