image: registry.gitlab.com/fdroid/ci-images-repomaker:latest

pep8:
  script:
    - ./tests/test-pep8.sh

pylint:
  before_script:
    - pip3 install -r requirements.txt

  script:
    - ./tests/test-pylint.sh

units:
  cache:
    paths:
      - /usr/local/lib/python3.5/dist-packages
      - node_modules

  before_script:
    - ./setup.sh
    - pip3 install -r requirements-dev.txt
    - npm install --user

  script:
    - ./tests/test-units.sh

docker:
  image: docker:git
  services:
    - docker:dind
  variables:
    IMAGE: registry.gitlab.com/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest

  before_script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} registry.gitlab.com
  script:
    - docker build -t $IMAGE .
    - docker push $IMAGE

  only:
    - master
